### ISSUE TITLE
Why does mocap clone `ch`, but not info?

### ISSUE THREAD

**Issue by JonasVautherin** [irsdkv/MAVSDK-Rust#1]
I'm new to Rust, and I don't understand [this](https://github.com/irsdkv/MAVSDK-Rust/blob/develop/src/lib.rs#L23-L24):

```rust
mocap: mocap::Mocap::new(ch.clone()),
info: info::Info::new(ch)
```

Why is it that the first one clones the channel, and the other one just takes it? Is that an ownership thing, where here `info` becomes the new owner of `ch` at the end of the list? So if we had more plugins, all of them would `ch.clone()` except for the last one?

And finally, shouldn't they all `ch.clone()`, so that the `System` keeps the ownership on the channel (what if it wants to close it, for instance?).

**Comment by irsdkv** [comment]
> Is that an ownership thing, where here info becomes the new owner of ch at the end of the list?

Yes, that's right

> So if we had more plugins, all of them would ch.clone() except for the last one?

And this is true :)

> Shouldn't they all ch.clone(), so that the System keeps the ownership on the channel (what if it wants to close it, for instance?).

Hm. That make sense. I will implement this

**Comment by irsdkv** [comment]
Now Trait `FromChannel` use reference and `clone()` called in implementation:
https://github.com/mavlink/MAVSDK-Rust/blob/89e1dddaee1174be4309ba28bef45fe000769ce0/src/lib.rs#L14
