### ISSUE TITLE
[question] committing generated code

### ISSUE THREAD

**Issue by danieleades** [irsdkv/MAVSDK-Rust#15]
Is it necessary to commit the generated code to VCS? I would have thought best practice would be to exclude it.
What is the purpose of including it?

**Comment by julianoes** [comment]
Good question. I think for C++ we did it so that you don't have to have the dependencies (e.g. protobuf) installed on the system, or built, and you can still build the project. For Rust I have no strong opinion. Is it easy to generate it as part of the build?

**Comment by danieleades** [comment]
> Good question. I think for C++ we did it so that you don't have to have the dependencies (e.g. protobuf) installed on the system, or built, and you can still build the project. For Rust I have no strong opinion. Is it easy to generate it as part of the build?

i'll play with it in #16 and see what it looks like.

While i'm at it, is there a reason the `Cargo.lock` file is committed?

**Comment by julianoes** [comment]
> While i'm at it, is there a reason the Cargo.lock file is committed?

Not sure. I would say do whatever Rust recommends.
