### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by JonasVautherin** [irsdkv/MAVSDK-Rust#2]
Looking at the [info example](https://github.com/irsdkv/MAVSDK-Rust/blob/develop/src/generated/info/mod.rs#L59-L60):

```rust
impl Info {
    pub fn get_version(&self) -> std::result::Result<GetVersionResponse, grpcio::Error> {
```

This exposes `grpcio::Error`. In the other language bindings, we try to minimize the exposure of gRPC by implementing our own errors wrapping them. So that if we ever want to remove gRPC, our API stays the same. Is that something we could consider here as well?

Also, I see that we return `Ok(...)` for all the autopilot results. But e.g. `InfoResult_Result::INFORMATION_NOT_RECEIVED_YET` is an error, and I believe it should be returned as an `Err(...)`. What do you think?

**Comment by irsdkv** [comment]
Error handling is one of the most important and beautiful sides of the Rust.
And we should work it out well.
May be make sense to do nested `Result` or `Enum`.
I will commit some improvements soon. Please looks on it.

**Comment by irsdkv** [comment]
So this is my [first version of Error handling](
https://github.com/mavlink/MAVSDK-Rust/commit/73cc8e65f5ffd87126fbfce750155dd4b123bcda#diff-b4aea3e418ccdb71239b96952d9cddb6R13-R25).
It is not too good as I want at this moment. And `grpcio::Error` still here. I will think about more clear implementation.
May be you have any ideas?

Current error messages:
- Request was not successful:
```bash
$ cargo run --example info
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/info`
Err(MavsdkError { result: InformationNotReceivedYet, result_str: "Information not received yet" })
```
- RPC Error:
```bash
$ cargo run --example info
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/info`
RpcErr(RpcFailure(RpcStatus { status: Unavailable, details: Some("Connect Failed") }))
```

**Comment by JonasVautherin** [comment]
I see that we have a `MavsdkError` type, so that's already something. I guess we could go with that and see later if we can abstract away the remaining `RpcErr`.

Just for my understanding:

```rust
#[derive(Debug)]
pub enum MavsdkResult<T, ErrT> {
    Ok(T),
    Err(MavsdkError<ErrT>),
    RpcErr(grpcio::Error)
}
```

Does this create some kind of new type `MavsdkResult` that may be an `Ok`, an `Err` or an `RpcErr`? Seems pretty cool because it can then be pattern matched, right? :sunglasses:

**Comment by irsdkv** [comment]
> Does this create some kind of new type `MavsdkResult` that may be an `Ok`, an `Err` or an `RpcErr`?

Yes you are right.
But we have one problem with it.
In case of `Err(error)`  user will should check `Success` match too. Something like that:

```rust
// Info module
enum InfoResult {
    Unknown = 0; //  --- ERROR ---
    Success = 1; // --- OK ---
    InformationNotReceivedYet = 2; //  --- ERROR ---
}
...
match info_result {
    Ok(version) => ...,
    RpCErr(rpc_err) => ...,
    Err(mavsdk_err) => match {
        Unknown => ...,
        InformationNotReceivedYet => ...,
        Success => ... // This place
    }
}
```

This is not too useful and I think about this solution:
 Use only non-`SUCCESS` enum members for internal plugin `Result` type (and so it will `InfoError`, not `InfoResult`).

Like that:

```rust
enum InfoError { // Now not InfoResult but InfoError
    Unknown = 0; //  --- ERROR ---
    InformationNotReceivedYet = 1; //  --- ERROR ---
}
```

 So we have only one way to  extract `SUCCESS` result:
```rust
match info_result {
    Ok(version) => ..., // Our `SUCCESS`-result
    ...
}
```
and also we will have way to know which exact error was occurs:
```rust
match info_result {
    Ok(version) => ...,
    RpcErr(rpc_err) => ...,
    Err(mavsdk_err) => match {
        Unknown => ...,
        InformationNotReceivedYet => ...,
        // Success => ...  !does not exist!
    }
}
```
What do you think about that?

**Comment by JonasVautherin** [comment]
Oh, right! I had not realized this. Your last version seems very nice, and I believe we should be able to auto-generate that (we assume everywhere that when a result exists, there is always a "SUCCESS").

So that looks good to me! :+1:

**Comment by irsdkv** [comment]
Hm. I think I have better idea:

```rust
// lib.rs 

pub enum RequestError<PluginMavErr> {
    MavErr(PluginMavErr),
    RpcErr(grpcio::Error)
}

pub enum Result<T, PluginMavErr> {
    Ok(T),
    Err(RequestError<PluginMavErr>)
}
```
So in `Info`, for example:
```rust
// info/mod.rs
enum InfoError { 
    Unknown = 0; 
    InformationNotReceivedYet = 1;
}
```
And check Info plugin result:
```rust
match info_result {
    Ok(version) => ...,
    Err(request_err) => match request_err {
        MavErr(mav_err) => match mav_err {
             Unknown => ...,
             InformationNotReceivedYet => ...,
        },
        RpcErr(rpc_err) => match rpc_err {
            ....
        }
    }
}
```

This way is more Rust-idiomatic because of `Result` type has only two cases: `Ok()` and `Err()`.
I will create PR with implementation. Will see on it.

**Comment by julianoes** [comment]
Or alternatively, can you add one error case to `MavErr` which is a `GrpcErr` and then contains the specific gRPC error as a string?

**Comment by irsdkv** [comment]
> Or alternatively, can you add one error case to MavErr which is a GrpcErr and then contains the specific gRPC error as a string?

I think that this is not a best way.
One of the most important goals of Rust is error handling. User should can and should have a process  every type of error. If we will wrap gRPC errors (and use for example only Error text representation) so user will not have an a simple ability to check which one error occurs. 
Also some errors have additional data:

```Rust
/// gRPC errors
#[derive(Debug)]
pub enum Error {
    /// Codec error.
    Codec(Box<dyn error::Error + Send + Sync>),
    /// Failed to start an internal async call.
    CallFailure(GrpcCallStatus), // This one
    /// Rpc request fail.
    RpcFailure(RpcStatus),  // This one
    /// Try to write to a finished rpc call.
    RpcFinished(Option<RpcStatus>),  // This one
    /// Remote is stopped.
    RemoteStopped,
    /// Failed to shutdown.
    ShutdownFailed,
    /// Failed to bind.
    BindFail(String, u16),  // This one
    /// gRPC completion queue is shutdown.
    QueueShutdown,  // This one
    /// Failed to create Google default credentials.
    GoogleAuthenticationFailed,
    /// Invalid format of metadata.
    InvalidMetadata(String),  // This one
}
```

I think that [one of the way we can go](#5) is include `RpcErr` in plugin's `Err`, but it seems like excessive encapsulation and errors mixing.
On the other hand it require a little bit less code in case of user prefer panic on every error :) 
And also `grpcio::Error` derive only `Debug`.

**Comment by JonasVautherin** [comment]
Ok, I think the current solution is good for now, we'll see how it goes :smile:. I think we can close this.
