### ISSUE TITLE
no_std environments

### ISSUE THREAD

**Issue by danieleades** [irsdkv/MAVSDK-Rust#22]
are there any plans to target `no_std` environments?

I have to admit it's not something i know loads about. I think in principle it shouldn't be *too* tricky.

One caveat i'm aware of is that `std::error::Error` doesn't exist, which would make #20 a non-starter (unless https://github.com/dtolnay/thiserror/pull/64 is merged)

**Comment by julianoes** [comment]
I would not expect that, in the same way that MAVSDK uses the STL. Would gRPC even work with `no_std`?

**Comment by danieleades** [comment]
> Would gRPC even work with `no_std`?

not 100% sure. According to the docs `prost` supports `no_std`. Not sure if `tonic` does. Although looking at the generated code, I can't see anything that obviously *won't* work...

**Comment by danieleades** [comment]
sounds like it's a non-goal for now in any case. I'll close this. #20 is safe for now!
