### ISSUE TITLE
Move to tonic gRPC client

### ISSUE THREAD

**Issue by irsdkv** [irsdkv/MAVSDK-Rust#7]
I propose to consider move from currently used [grpcio](https://github.com/pingcap/grpc-rs) to [tonic](https://github.com/hyperium/tonic) gRPC client.

Reasons:
 - MIT license vs Apache 2.0
 - [Based on](https://github.com/hyperium/tonic#overview) rapidly evolving `tokio` framework
 - "First class support" of async/await
 - On actively developing

What do you think about it?

**Comment by julianoes** [comment]
I guess I don't have an opinion as long as it works :smile:.

**Comment by JonasVautherin** [comment]
Same for me, tonic seems good as well :+1:, and I like the idea of the `async`/`await` support.

Just out of curiosity, why is it better to have MIT than Apache 2?

**Comment by irsdkv** [comment]
> why is it better to have MIT than Apache 2

MITlooks like more permissive. But for the most part I just like it :)

**Comment by irsdkv** [comment]
Okay, lets go with `tonic`
